import type { Course, QuizQuestion } from './types';

/**
 * A curated catalog of real, free/open resources — official docs, well-known YouTube
 * channels, and established free-course platforms. Every resourceUrl below points at a
 * real, stable landing page (a channel, official docs hub, or course index), not a
 * specific video ID we can't verify — so nothing here is a fabricated link. Content
 * (description/curriculum) is written by us; the linked resource is the actual teaching
 * material.
 */
export const COURSES: Course[] = [
  // ---------- Programming fundamentals ----------
  {
    id: 'c-py-basics',
    title: 'Python Programming Fundamentals',
    category: 'Programming',
    skillTags: ['Programming & Software Dev'],
    level: 'Beginner',
    provider: 'freeCodeCamp',
    resourceUrl: 'https://www.freecodecamp.org/learn/scientific-computing-with-python/',
    resourceType: 'Free Course',
    description: 'Core Python syntax, data structures, and functions through freeCodeCamp\'s free certification track.',
    curriculum: ['Variables & data types', 'Control flow', 'Functions & modules', 'Lists, dicts & sets', 'File I/O', 'Mini capstone project'],
    estimatedHours: 20,
    quizCategory: 'programming-fundamentals',
  },
  {
    id: 'c-py-corey',
    title: 'Python Deep Dive',
    category: 'Programming',
    skillTags: ['Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'Corey Schafer (YouTube)',
    resourceUrl: 'https://www.youtube.com/@coreyms',
    resourceType: 'YouTube Channel',
    description: 'One of the most respected Python educators on YouTube — OOP, decorators, generators, and idiomatic Python.',
    curriculum: ['OOP in Python', 'Decorators & generators', 'Error handling', 'Virtual environments', 'Testing with unittest'],
    estimatedHours: 12,
    quizCategory: 'programming-fundamentals',
  },
  {
    id: 'c-js-basics',
    title: 'JavaScript Fundamentals',
    category: 'Programming',
    skillTags: ['Programming & Software Dev'],
    level: 'Beginner',
    provider: 'freeCodeCamp',
    resourceUrl: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
    resourceType: 'Free Course',
    description: 'The de-facto free standard for learning JS from scratch, including algorithms and data structures.',
    curriculum: ['Syntax & data types', 'Functions & scope', 'Arrays & objects', 'ES6+ features', 'Algorithmic thinking'],
    estimatedHours: 25,
    quizCategory: 'programming-fundamentals',
  },
  {
    id: 'c-cpp-basics',
    title: 'C++ for Beginners',
    category: 'Programming',
    skillTags: ['Programming & Software Dev'],
    level: 'Beginner',
    provider: 'freeCodeCamp (YouTube)',
    resourceUrl: 'https://www.youtube.com/@freecodecamp',
    resourceType: 'YouTube Channel',
    description: 'A full free-standing C++ course covering syntax through pointers and memory management.',
    curriculum: ['Syntax & compilation', 'Control flow', 'Functions & pointers', 'OOP basics', 'STL containers'],
    estimatedHours: 15,
    quizCategory: 'programming-fundamentals',
  },
  {
    id: 'c-java-basics',
    title: 'Java Programming Bootcamp',
    category: 'Programming',
    skillTags: ['Programming & Software Dev'],
    level: 'Beginner',
    provider: 'Programming with Mosh',
    resourceUrl: 'https://www.youtube.com/@programmingwithmosh',
    resourceType: 'YouTube Channel',
    description: 'Clear, structured Java fundamentals through OOP concepts, from a widely-followed instructor.',
    curriculum: ['Syntax & types', 'OOP: classes & inheritance', 'Collections', 'Exception handling', 'Basic multithreading'],
    estimatedHours: 14,
    quizCategory: 'programming-fundamentals',
  },
  {
    id: 'c-dsa',
    title: 'Data Structures & Algorithms',
    category: 'Programming',
    skillTags: ['Programming & Software Dev', 'Problem Solving'],
    level: 'Intermediate',
    provider: 'freeCodeCamp',
    resourceUrl: 'https://www.freecodecamp.org/learn/coding-interview-prep/',
    resourceType: 'Free Course',
    description: 'Interview-grade coverage of core data structures and algorithmic patterns.',
    curriculum: ['Arrays & strings', 'Trees & graphs', 'Sorting & searching', 'Dynamic programming', 'Big-O analysis'],
    estimatedHours: 30,
    quizCategory: 'programming-fundamentals',
  },
  {
    id: 'c-git',
    title: 'Git & Version Control',
    category: 'Programming',
    skillTags: ['Programming & Software Dev'],
    level: 'Beginner',
    provider: 'Pro Git (official book)',
    resourceUrl: 'https://git-scm.com/book/en/v2',
    resourceType: 'Documentation',
    description: 'The free, official Git book — from first commit to branching strategies used in real teams.',
    curriculum: ['Init, add, commit', 'Branching & merging', 'Remotes & collaboration', 'Rebasing', 'Resolving conflicts'],
    estimatedHours: 6,
    quizCategory: 'version-control',
  },

  // ---------- Web development ----------
  {
    id: 'c-html-css',
    title: 'HTML & CSS from Scratch',
    category: 'Web Development',
    skillTags: ['Programming & Software Dev', 'UI / UX Design'],
    level: 'Beginner',
    provider: 'freeCodeCamp',
    resourceUrl: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    resourceType: 'Free Course',
    description: 'Responsive web design certification covering semantic HTML and modern CSS layout.',
    curriculum: ['Semantic HTML', 'Box model & flexbox', 'CSS Grid', 'Responsive media queries', 'Accessibility basics'],
    estimatedHours: 16,
    quizCategory: 'web-dev',
  },
  {
    id: 'c-react',
    title: 'React — Official Docs Walkthrough',
    category: 'Web Development',
    skillTags: ['Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'React (official)',
    resourceUrl: 'https://react.dev/learn',
    resourceType: 'Documentation',
    description: 'The current official React documentation and interactive tutorial — the most reliable source for React itself.',
    curriculum: ['Components & JSX', 'State & props', 'Effects & lifecycle', 'Hooks', 'Thinking in React'],
    estimatedHours: 14,
    quizCategory: 'web-dev',
  },
  {
    id: 'c-node',
    title: 'Node.js & Backend APIs',
    category: 'Web Development',
    skillTags: ['Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'Node.js (official)',
    resourceUrl: 'https://nodejs.org/en/learn/getting-started/introduction-to-nodejs',
    resourceType: 'Documentation',
    description: 'Official Node.js learning path for building servers and REST APIs.',
    curriculum: ['Event loop & modules', 'HTTP servers', 'Express basics', 'REST API design', 'Middleware & error handling'],
    estimatedHours: 12,
    quizCategory: 'web-dev',
  },
  {
    id: 'c-webdev-traversy',
    title: 'Full-Stack Web Development Crash Courses',
    category: 'Web Development',
    skillTags: ['Programming & Software Dev'],
    level: 'Beginner',
    provider: 'Traversy Media (YouTube)',
    resourceUrl: 'https://www.youtube.com/@TraversyMedia',
    resourceType: 'YouTube Channel',
    description: 'One of the most popular web dev channels — fast, practical crash courses across the stack.',
    curriculum: ['Modern JS crash course', 'React crash course', 'Node/Express crash course', 'MongoDB basics', 'Deployment basics'],
    estimatedHours: 18,
    quizCategory: 'web-dev',
  },
  {
    id: 'c-webdev-netninja',
    title: 'Modern Web Dev Playlist Series',
    category: 'Web Development',
    skillTags: ['Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'The Net Ninja (YouTube)',
    resourceUrl: 'https://www.youtube.com/@NetNinja',
    resourceType: 'YouTube Channel',
    description: 'Well-structured playlist series on frontend frameworks, CSS, and backend basics.',
    curriculum: ['Vue/React fundamentals', 'Tailwind CSS', 'Firebase basics', 'Async JavaScript', 'API integration'],
    estimatedHours: 15,
    quizCategory: 'web-dev',
  },
  {
    id: 'c-testing',
    title: 'Testing Web Applications',
    category: 'Web Development',
    skillTags: ['Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'Testing Library (official)',
    resourceUrl: 'https://testing-library.com/docs/',
    resourceType: 'Documentation',
    description: 'Official docs for the most widely used frontend testing approach today.',
    curriculum: ['Unit vs integration tests', 'Query priorities', 'User-event simulation', 'Mocking', 'CI integration basics'],
    estimatedHours: 8,
    quizCategory: 'web-dev',
  },

  // ---------- Mobile development ----------
  {
    id: 'c-android',
    title: 'Android App Development',
    category: 'Mobile Development',
    skillTags: ['Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'Android Developers (official)',
    resourceUrl: 'https://developer.android.com/courses',
    resourceType: 'Documentation',
    description: 'Google\'s own free Android development courses, kept current with the latest tooling.',
    curriculum: ['Kotlin basics', 'Activities & layouts', 'Jetpack Compose', 'Navigation', 'Local storage'],
    estimatedHours: 20,
    quizCategory: 'mobile-dev',
  },
  {
    id: 'c-ios',
    title: 'iOS Development with SwiftUI',
    category: 'Mobile Development',
    skillTags: ['Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'Apple Developer (official)',
    resourceUrl: 'https://developer.apple.com/tutorials/swiftui',
    resourceType: 'Documentation',
    description: 'Apple\'s official interactive SwiftUI tutorials for building native iOS apps.',
    curriculum: ['Swift basics', 'SwiftUI views', 'State management', 'Navigation', 'Data persistence'],
    estimatedHours: 18,
    quizCategory: 'mobile-dev',
  },

  // ---------- Databases ----------
  {
    id: 'c-sql',
    title: 'SQL Fundamentals',
    category: 'Databases',
    skillTags: ['Data Analysis & Statistics', 'Programming & Software Dev'],
    level: 'Beginner',
    provider: 'PostgreSQL (official)',
    resourceUrl: 'https://www.postgresql.org/docs/current/tutorial.html',
    resourceType: 'Documentation',
    description: 'PostgreSQL\'s official tutorial — a rigorous, free way to learn real-world SQL.',
    curriculum: ['SELECT & filtering', 'Joins', 'Aggregation & grouping', 'Subqueries', 'Indexes basics'],
    estimatedHours: 10,
    quizCategory: 'databases',
  },
  {
    id: 'c-mongo',
    title: 'NoSQL with MongoDB',
    category: 'Databases',
    skillTags: ['Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'MongoDB (official)',
    resourceUrl: 'https://www.mongodb.com/docs/manual/tutorial/',
    resourceType: 'Documentation',
    description: 'Official MongoDB tutorials for document-based data modeling.',
    curriculum: ['Documents & collections', 'CRUD operations', 'Aggregation pipeline', 'Indexing', 'Schema design patterns'],
    estimatedHours: 9,
    quizCategory: 'databases',
  },

  // ---------- Data science & AI/ML ----------
  {
    id: 'c-ds-intro',
    title: 'Data Analysis with Python',
    category: 'Data Science',
    skillTags: ['Data Analysis & Statistics'],
    level: 'Beginner',
    provider: 'freeCodeCamp',
    resourceUrl: 'https://www.freecodecamp.org/learn/data-analysis-with-python/',
    resourceType: 'Free Course',
    description: 'Pandas, NumPy, and Matplotlib through freeCodeCamp\'s data analysis certification.',
    curriculum: ['NumPy arrays', 'Pandas DataFrames', 'Data cleaning', 'Visualization with Matplotlib', 'Exploratory data analysis'],
    estimatedHours: 20,
    quizCategory: 'data-science',
  },
  {
    id: 'c-ds-codebasics',
    title: 'Practical Data Science Projects',
    category: 'Data Science',
    skillTags: ['Data Analysis & Statistics'],
    level: 'Intermediate',
    provider: 'codebasics (YouTube)',
    resourceUrl: 'https://www.youtube.com/@codebasics',
    resourceType: 'YouTube Channel',
    description: 'Project-driven data science and analytics tutorials, popular for practical case studies.',
    curriculum: ['Data wrangling', 'Feature engineering', 'Regression models', 'Model evaluation', 'End-to-end case study'],
    estimatedHours: 16,
    quizCategory: 'data-science',
  },
  {
    id: 'c-stats',
    title: 'Statistics for Data Science',
    category: 'Data Science',
    skillTags: ['Data Analysis & Statistics'],
    level: 'Beginner',
    provider: 'Khan Academy',
    resourceUrl: 'https://www.khanacademy.org/math/statistics-probability',
    resourceType: 'Free Course',
    description: 'Khan Academy\'s complete, free statistics & probability curriculum.',
    curriculum: ['Descriptive statistics', 'Probability basics', 'Distributions', 'Hypothesis testing', 'Regression intuition'],
    estimatedHours: 18,
    quizCategory: 'data-science',
  },
  {
    id: 'c-ml-sentdex',
    title: 'Machine Learning with Python',
    category: 'AI / ML',
    skillTags: ['AI / Machine Learning'],
    level: 'Intermediate',
    provider: 'sentdex (YouTube)',
    resourceUrl: 'https://www.youtube.com/@sentdex',
    resourceType: 'YouTube Channel',
    description: 'Long-running, well-regarded practical machine learning and Python tutorials.',
    curriculum: ['scikit-learn basics', 'Classification & regression', 'Clustering', 'Model tuning', 'Practical ML pipelines'],
    estimatedHours: 18,
    quizCategory: 'ai-ml',
  },
  {
    id: 'c-ml-intuition',
    title: 'Neural Networks — Visual Intuition',
    category: 'AI / ML',
    skillTags: ['AI / Machine Learning'],
    level: 'Beginner',
    provider: '3Blue1Brown (YouTube)',
    resourceUrl: 'https://www.youtube.com/@3blue1brown',
    resourceType: 'YouTube Channel',
    description: 'The gold standard for visual, intuitive explanations of how neural networks actually work.',
    curriculum: ['What is a neural network', 'Gradient descent', 'Backpropagation', 'Convolutional networks intuition', 'Transformers intuition'],
    estimatedHours: 6,
    quizCategory: 'ai-ml',
  },
  {
    id: 'c-tensorflow',
    title: 'Deep Learning with TensorFlow',
    category: 'AI / ML',
    skillTags: ['AI / Machine Learning', 'Programming & Software Dev'],
    level: 'Advanced',
    provider: 'TensorFlow (official)',
    resourceUrl: 'https://www.tensorflow.org/tutorials',
    resourceType: 'Documentation',
    description: 'Official TensorFlow tutorials, from basic models to computer vision and NLP.',
    curriculum: ['Tensors & keras basics', 'Image classification', 'Text classification', 'Model saving/serving', 'Transfer learning'],
    estimatedHours: 20,
    quizCategory: 'ai-ml',
  },
  {
    id: 'c-pytorch',
    title: 'Deep Learning with PyTorch',
    category: 'AI / ML',
    skillTags: ['AI / Machine Learning', 'Programming & Software Dev'],
    level: 'Advanced',
    provider: 'PyTorch (official)',
    resourceUrl: 'https://pytorch.org/tutorials/',
    resourceType: 'Documentation',
    description: 'Official PyTorch tutorials — the dominant framework in ML research today.',
    curriculum: ['Tensors & autograd', 'Building neural nets', 'Training loops', 'Datasets & dataloaders', 'Transfer learning'],
    estimatedHours: 20,
    quizCategory: 'ai-ml',
  },
  {
    id: 'c-krish-ml',
    title: 'End-to-End ML & Data Science Projects',
    category: 'AI / ML',
    skillTags: ['AI / Machine Learning', 'Data Analysis & Statistics'],
    level: 'Intermediate',
    provider: 'Krish Naik (YouTube)',
    resourceUrl: 'https://www.youtube.com/@krishnaik06',
    resourceType: 'YouTube Channel',
    description: 'Widely followed applied ML and MLOps content, from fundamentals to deployment.',
    curriculum: ['Applied ML workflow', 'Feature engineering', 'Model deployment basics', 'MLOps intro', 'Interview-style projects'],
    estimatedHours: 15,
    quizCategory: 'ai-ml',
  },

  // ---------- Cloud & DevOps ----------
  {
    id: 'c-aws',
    title: 'AWS Cloud Practitioner Essentials',
    category: 'Cloud & DevOps',
    skillTags: ['Cloud & DevOps'],
    level: 'Beginner',
    provider: 'AWS Skill Builder (official)',
    resourceUrl: 'https://aws.amazon.com/training/digital/',
    resourceType: 'Free Course',
    description: 'AWS\'s own free digital training hub — the standard starting point for cloud fundamentals.',
    curriculum: ['Core AWS services', 'IAM & security basics', 'Compute (EC2)', 'Storage (S3)', 'Pricing & support models'],
    estimatedHours: 12,
    quizCategory: 'cloud-devops',
  },
  {
    id: 'c-azure',
    title: 'Microsoft Azure Fundamentals',
    category: 'Cloud & DevOps',
    skillTags: ['Cloud & DevOps'],
    level: 'Beginner',
    provider: 'Microsoft Learn (official)',
    resourceUrl: 'https://learn.microsoft.com/en-us/training/azure/',
    resourceType: 'Free Course',
    description: 'Microsoft\'s official, free, self-paced Azure learning paths.',
    curriculum: ['Cloud concepts', 'Azure core services', 'Identity & governance', 'Pricing & SLAs', 'Azure portal basics'],
    estimatedHours: 10,
    quizCategory: 'cloud-devops',
  },
  {
    id: 'c-gcp',
    title: 'Google Cloud Fundamentals',
    category: 'Cloud & DevOps',
    skillTags: ['Cloud & DevOps'],
    level: 'Beginner',
    provider: 'Google Cloud (official)',
    resourceUrl: 'https://cloud.google.com/training',
    resourceType: 'Free Course',
    description: 'Google\'s own training hub covering core GCP services and free-tier hands-on labs.',
    curriculum: ['Compute Engine basics', 'Cloud Storage', 'IAM basics', 'BigQuery intro', 'Pricing basics'],
    estimatedHours: 10,
    quizCategory: 'cloud-devops',
  },
  {
    id: 'c-docker',
    title: 'Docker — Getting Started',
    category: 'Cloud & DevOps',
    skillTags: ['Cloud & DevOps'],
    level: 'Beginner',
    provider: 'Docker (official)',
    resourceUrl: 'https://www.docker.com/101-tutorial/',
    resourceType: 'Documentation',
    description: 'Docker\'s own interactive 101 tutorial for containerizing applications.',
    curriculum: ['Images vs containers', 'Writing a Dockerfile', 'Volumes & networking', 'Docker Compose', 'Best practices'],
    estimatedHours: 6,
    quizCategory: 'cloud-devops',
  },
  {
    id: 'c-k8s',
    title: 'Kubernetes Basics',
    category: 'Cloud & DevOps',
    skillTags: ['Cloud & DevOps'],
    level: 'Intermediate',
    provider: 'Kubernetes (official)',
    resourceUrl: 'https://kubernetes.io/docs/tutorials/',
    resourceType: 'Documentation',
    description: 'The official Kubernetes tutorials — pods, deployments, and services from the source.',
    curriculum: ['Pods & deployments', 'Services & networking', 'ConfigMaps & secrets', 'Scaling', 'Rolling updates'],
    estimatedHours: 10,
    quizCategory: 'cloud-devops',
  },

  // ---------- Cybersecurity ----------
  {
    id: 'c-sec-fundamentals',
    title: 'Cybersecurity Fundamentals',
    category: 'Cybersecurity',
    skillTags: ['Cybersecurity'],
    level: 'Beginner',
    provider: 'SANS CyberAces (official, free)',
    resourceUrl: 'https://www.sans.org/cyberaces/',
    resourceType: 'Free Course',
    description: 'SANS\'s own free introductory cybersecurity tutorials, covering networking through security basics.',
    curriculum: ['Networking fundamentals', 'Operating system security', 'System administration', 'Introductory security concepts'],
    estimatedHours: 12,
    quizCategory: 'cybersecurity',
  },
  {
    id: 'c-owasp',
    title: 'Web Application Security (OWASP Top 10)',
    category: 'Cybersecurity',
    skillTags: ['Cybersecurity', 'Programming & Software Dev'],
    level: 'Intermediate',
    provider: 'OWASP (official)',
    resourceUrl: 'https://owasp.org/www-project-top-ten/',
    resourceType: 'Documentation',
    description: 'The industry-standard reference for the most critical web application security risks.',
    curriculum: ['Injection flaws', 'Broken authentication', 'XSS', 'Security misconfiguration', 'Secure coding practices'],
    estimatedHours: 8,
    quizCategory: 'cybersecurity',
  },
  {
    id: 'c-networking-sec',
    title: 'Networking for Security',
    category: 'Cybersecurity',
    skillTags: ['Cybersecurity'],
    level: 'Beginner',
    provider: 'NetworkChuck (YouTube)',
    resourceUrl: 'https://www.youtube.com/@NetworkChuck',
    resourceType: 'YouTube Channel',
    description: 'Highly engaging, practical networking and security content for beginners.',
    curriculum: ['TCP/IP basics', 'Subnetting', 'VPNs & firewalls', 'DNS & routing', 'Home lab security basics'],
    estimatedHours: 10,
    quizCategory: 'cybersecurity',
  },
  {
    id: 'c-ethical-hacking',
    title: 'Ethical Hacking Fundamentals',
    category: 'Cybersecurity',
    skillTags: ['Cybersecurity', 'Problem Solving'],
    level: 'Intermediate',
    provider: 'TryHackMe',
    resourceUrl: 'https://tryhackme.com/',
    resourceType: 'Free Course',
    description: 'Hands-on, gamified security labs with a substantial free tier — learn by doing.',
    curriculum: ['Reconnaissance basics', 'Common vulnerabilities', 'Privilege escalation', 'Web exploitation basics', 'Reporting findings'],
    estimatedHours: 15,
    quizCategory: 'cybersecurity',
  },

  // ---------- Design / UX ----------
  {
    id: 'c-figma',
    title: 'UI Design with Figma',
    category: 'Design',
    skillTags: ['UI / UX Design'],
    level: 'Beginner',
    provider: 'Figma (official)',
    resourceUrl: 'https://www.figma.com/resources/learn-design/',
    resourceType: 'Free Course',
    description: 'Figma\'s own free design-learning hub, from tool basics to design systems.',
    curriculum: ['Interface basics', 'Components & auto layout', 'Prototyping', 'Design systems', 'Handoff to developers'],
    estimatedHours: 10,
    quizCategory: 'design-ux',
  },
  {
    id: 'c-uxprinciples',
    title: 'UX Laws & Principles',
    category: 'Design',
    skillTags: ['UI / UX Design'],
    level: 'Beginner',
    provider: 'Laws of UX',
    resourceUrl: 'https://lawsofux.com/',
    resourceType: 'Documentation',
    description: 'A concise, well-respected reference of psychological principles behind good UX.',
    curriculum: ['Fitts\'s Law', "Hick's Law", 'Jakob\'s Law', 'Cognitive load', 'Visual hierarchy'],
    estimatedHours: 4,
    quizCategory: 'design-ux',
  },
  {
    id: 'c-nngroup',
    title: 'UX Research Fundamentals',
    category: 'Design',
    skillTags: ['UI / UX Design', 'Communication'],
    level: 'Intermediate',
    provider: 'Nielsen Norman Group',
    resourceUrl: 'https://www.nngroup.com/articles/',
    resourceType: 'Documentation',
    description: 'The most cited authority in UX research, with a large free article library.',
    curriculum: ['Usability testing basics', 'User interviews', 'Card sorting', 'Heuristic evaluation', 'Reporting insights'],
    estimatedHours: 8,
    quizCategory: 'design-ux',
  },
  {
    id: 'c-designcourse',
    title: 'Practical UI/UX Design Projects',
    category: 'Design',
    skillTags: ['UI / UX Design'],
    level: 'Intermediate',
    provider: 'DesignCourse (YouTube)',
    resourceUrl: 'https://www.youtube.com/@DesignCourse',
    resourceType: 'YouTube Channel',
    description: 'Practical, project-based UI/UX tutorials from a well-known design educator.',
    curriculum: ['Landing page design', 'Design systems in practice', 'Mobile app design', 'Portfolio case studies', 'Client feedback handling'],
    estimatedHours: 10,
    quizCategory: 'design-ux',
  },

  // ---------- Digital marketing / business ----------
  {
    id: 'c-google-marketing',
    title: 'Digital Marketing Fundamentals',
    category: 'Marketing',
    skillTags: ['Digital Marketing'],
    level: 'Beginner',
    provider: 'Google Skillshop (official)',
    resourceUrl: 'https://skillshop.withgoogle.com/',
    resourceType: 'Free Course',
    description: 'Google\'s own free certified courses on search, analytics, and digital marketing.',
    curriculum: ['Search fundamentals', 'Google Analytics basics', 'SEO fundamentals', 'Ads basics', 'Measuring campaign success'],
    estimatedHours: 10,
    quizCategory: 'digital-marketing',
  },
  {
    id: 'c-hubspot',
    title: 'Inbound & Content Marketing',
    category: 'Marketing',
    skillTags: ['Digital Marketing', 'Communication'],
    level: 'Beginner',
    provider: 'HubSpot Academy',
    resourceUrl: 'https://www.hubspot.com/academy',
    resourceType: 'Free Course',
    description: 'HubSpot\'s free, certificate-backed marketing and sales courses.',
    curriculum: ['Inbound methodology', 'Content strategy', 'Email marketing', 'Social media strategy', 'Lead nurturing'],
    estimatedHours: 12,
    quizCategory: 'digital-marketing',
  },
  {
    id: 'c-growth',
    title: 'Growth Marketing Tactics',
    category: 'Marketing',
    skillTags: ['Digital Marketing', 'Data Analysis & Statistics'],
    level: 'Intermediate',
    provider: 'Neil Patel (YouTube)',
    resourceUrl: 'https://www.youtube.com/@neilpatel',
    resourceType: 'YouTube Channel',
    description: 'Practical, data-driven growth marketing tactics from a well-known marketer.',
    curriculum: ['SEO tactics', 'Conversion rate optimization', 'A/B testing basics', 'Funnel analysis', 'Content distribution'],
    estimatedHours: 8,
    quizCategory: 'digital-marketing',
  },
  {
    id: 'c-finance-basics',
    title: 'Personal & Business Finance Basics',
    category: 'Business',
    skillTags: [],
    level: 'Beginner',
    provider: 'Khan Academy',
    resourceUrl: 'https://www.khanacademy.org/economics-finance-domain/core-finance',
    resourceType: 'Free Course',
    description: 'Khan Academy\'s free finance curriculum, from budgeting to how markets work.',
    curriculum: ['Budgeting basics', 'Interest & loans', 'Stocks & bonds basics', 'Financial statements', 'Business finance basics'],
    estimatedHours: 10,
    quizCategory: 'business-pm',
  },
  {
    id: 'c-pm-basics',
    title: 'Project Management Foundations',
    category: 'Business',
    skillTags: ['Product & Project Management'],
    level: 'Beginner',
    provider: 'PMI (official learning hub)',
    resourceUrl: 'https://www.pmi.org/learning',
    resourceType: 'Free Course',
    description: 'Foundational project management concepts from the field\'s leading professional body.',
    curriculum: ['Project lifecycle', 'Scope & schedule management', 'Risk management basics', 'Stakeholder communication', 'Agile basics'],
    estimatedHours: 8,
    quizCategory: 'business-pm',
  },
  {
    id: 'c-entrepreneurship',
    title: 'Startup & Entrepreneurship Basics',
    category: 'Business',
    skillTags: ['Product & Project Management', 'Leadership'],
    level: 'Beginner',
    provider: 'Y Combinator (Startup School, official)',
    resourceUrl: 'https://www.startupschool.org/',
    resourceType: 'Free Course',
    description: "Y Combinator's own free startup curriculum, taught by experienced founders and investors.",
    curriculum: ['Idea validation', 'Finding product-market fit', 'Basic fundraising concepts', 'Growth basics', 'Hiring basics'],
    estimatedHours: 10,
    quizCategory: 'business-pm',
  },

  // ---------- Soft skills ----------
  {
    id: 'c-comm-ted',
    title: 'Communication Skills through TED Talks',
    category: 'Soft Skills',
    skillTags: ['Communication'],
    level: 'Beginner',
    provider: 'TED (official channel)',
    resourceUrl: 'https://www.youtube.com/@TED',
    resourceType: 'YouTube Channel',
    description: 'Study how the world\'s best communicators structure and deliver ideas.',
    curriculum: ['Storytelling structure', 'Body language basics', 'Handling Q&A', 'Simplifying complex ideas', 'Persuasive speaking'],
    estimatedHours: 6,
    quizCategory: 'soft-skills',
  },
  {
    id: 'c-learning-how-to-learn',
    title: 'Learning How to Learn',
    category: 'Soft Skills',
    skillTags: ['Adaptability', 'Problem Solving'],
    level: 'Beginner',
    provider: 'Coursera (audit free)',
    resourceUrl: 'https://www.coursera.org/learn/learning-how-to-learn',
    resourceType: 'Free Course',
    description: 'One of the most-enrolled free courses ever — the science of effective learning.',
    curriculum: ['Focused vs diffuse thinking', 'Memory techniques', 'Avoiding procrastination', 'Chunking concepts', 'Effective practice'],
    estimatedHours: 8,
    quizCategory: 'soft-skills',
  },
  {
    id: 'c-time-mgmt',
    title: 'Time Management & Productivity',
    category: 'Soft Skills',
    skillTags: ['Time Management'],
    level: 'Beginner',
    provider: 'MindTools',
    resourceUrl: 'https://www.mindtools.com/',
    resourceType: 'Documentation',
    description: 'A long-standing, well-regarded library of practical productivity and management techniques.',
    curriculum: ['Prioritization frameworks', 'Eisenhower matrix', 'Avoiding burnout', 'Focus techniques', 'Goal-setting frameworks'],
    estimatedHours: 5,
    quizCategory: 'soft-skills',
  },
  {
    id: 'c-leadership',
    title: 'Leadership Fundamentals',
    category: 'Soft Skills',
    skillTags: ['Leadership', 'Teamwork & Collaboration'],
    level: 'Beginner',
    provider: 'MindTools',
    resourceUrl: 'https://www.mindtools.com/',
    resourceType: 'Documentation',
    description: 'Foundational leadership frameworks and team-management techniques.',
    curriculum: ['Leadership styles', 'Delegation', 'Giving feedback', 'Conflict resolution', 'Motivating a team'],
    estimatedHours: 6,
    quizCategory: 'soft-skills',
  },
  {
    id: 'c-teamwork',
    title: 'Teamwork & Collaboration Skills',
    category: 'Soft Skills',
    skillTags: ['Teamwork & Collaboration', 'Communication'],
    level: 'Beginner',
    provider: 'MindTools',
    resourceUrl: 'https://www.mindtools.com/',
    resourceType: 'Documentation',
    description: 'Practical frameworks for working effectively in cross-functional teams.',
    curriculum: ['Team roles', 'Effective meetings', 'Giving/receiving feedback', 'Remote collaboration', 'Conflict basics'],
    estimatedHours: 5,
    quizCategory: 'soft-skills',
  },
  {
    id: 'c-problem-solving',
    title: 'Structured Problem Solving',
    category: 'Soft Skills',
    skillTags: ['Problem Solving'],
    level: 'Beginner',
    provider: 'Khan Academy',
    resourceUrl: 'https://www.khanacademy.org/computing/computer-science/algorithms',
    resourceType: 'Free Course',
    description: 'Algorithmic and structured thinking approaches that transfer well beyond coding.',
    curriculum: ['Breaking down problems', 'Algorithmic thinking', 'Root-cause analysis', 'Decision trees', 'Trade-off analysis'],
    estimatedHours: 8,
    quizCategory: 'soft-skills',
  },
];

export const CATEGORIES = Array.from(new Set(COURSES.map((c) => c.category)));

/**
 * Shared per-category quiz banks (rather than one unique quiz per course) — keeps every
 * question genuinely authored and correct instead of thin/repetitive filler across 40+
 * individual courses. A 70%+ score is required to pass and earn a certificate.
 */
export const QUIZ_BANKS: Record<string, QuizQuestion[]> = {
  'programming-fundamentals': [
    { id: 'q1', question: 'What does "DRY" stand for in software engineering?', options: ['Do Repeat Yourself', "Don't Repeat Yourself", 'Data Retrieval Yield', 'Dynamic Runtime Yield'], correctIndex: 1 },
    { id: 'q2', question: 'Which data structure uses LIFO (Last In, First Out) ordering?', options: ['Queue', 'Stack', 'Linked list', 'Hash map'], correctIndex: 1 },
    { id: 'q3', question: 'What is the time complexity of binary search on a sorted array?', options: ['O(n)', 'O(n log n)', 'O(log n)', 'O(1)'], correctIndex: 2 },
    { id: 'q4', question: 'In most languages, what does a function returning "void" mean?', options: ['It always throws an error', 'It returns nothing', 'It returns null only', 'It runs asynchronously'], correctIndex: 1 },
    { id: 'q5', question: 'What is version control primarily used for?', options: ['Compiling code faster', 'Tracking and managing changes to code over time', 'Encrypting source code', 'Formatting code style'], correctIndex: 1 },
  ],
  'version-control': [
    { id: 'q1', question: 'What command creates a new local branch in Git?', options: ['git branch <name>', 'git commit <name>', 'git push <name>', 'git clone <name>'], correctIndex: 0 },
    { id: 'q2', question: 'What does "git commit" do?', options: ['Uploads code to a remote server', 'Saves a snapshot of staged changes to history', 'Deletes uncommitted changes', 'Creates a new repository'], correctIndex: 1 },
    { id: 'q3', question: 'What is a merge conflict?', options: ['A network error during push', 'When Git cannot automatically reconcile differing changes to the same lines', 'A missing commit message', 'A corrupted repository'], correctIndex: 1 },
    { id: 'q4', question: 'What does "git clone" do?', options: ['Creates a copy of a remote repository locally', 'Deletes a branch', 'Merges two branches', 'Reverts the last commit'], correctIndex: 0 },
    { id: 'q5', question: 'Which file tells Git which files to ignore?', options: ['.gitconfig', '.gitignore', '.gitattributes', 'README.md'], correctIndex: 1 },
  ],
  'web-dev': [
    { id: 'q1', question: 'What does CSS stand for?', options: ['Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style System', 'Colorful Style Syntax'], correctIndex: 1 },
    { id: 'q2', question: 'Which HTTP method is typically used to submit new data to a server?', options: ['GET', 'POST', 'DELETE', 'HEAD'], correctIndex: 1 },
    { id: 'q3', question: 'In React, what triggers a component to re-render?', options: ['Changing a CSS class externally', 'A change in state or props', 'Refreshing the browser only', 'Adding a comment in code'], correctIndex: 1 },
    { id: 'q4', question: 'What does REST stand for in "REST API"?', options: ['Rapid Execution State Transfer', 'Representational State Transfer', 'Remote End-State Transmission', 'Reactive State Transform'], correctIndex: 1 },
    { id: 'q5', question: 'What is the purpose of CSS Flexbox?', options: ['Encrypting stylesheets', 'Arranging items in flexible one-dimensional layouts', 'Compiling SASS files', 'Validating HTML syntax'], correctIndex: 1 },
  ],
  'mobile-dev': [
    { id: 'q1', question: 'Which language is primary for modern native Android development?', options: ['Swift', 'Kotlin', 'Objective-C', 'Dart'], correctIndex: 1 },
    { id: 'q2', question: 'What UI framework does Apple recommend for new iOS apps?', options: ['UIKit only', 'SwiftUI', 'React Native', 'Flutter'], correctIndex: 1 },
    { id: 'q3', question: 'What is an "Activity" in Android development?', options: ['A background network call', 'A single, focused screen with a user interface', 'A database table', 'A type of animation'], correctIndex: 1 },
    { id: 'q4', question: 'Why is local data persistence important in mobile apps?', options: ['It makes apps larger', 'It lets apps retain data between sessions without network access', 'It is required by app stores only for games', 'It replaces the need for a UI'], correctIndex: 1 },
    { id: 'q5', question: 'What does "responsive layout" mean in mobile development?', options: ['The app responds to server pings only', 'The UI adapts to different screen sizes', 'The app has fast API responses', 'The app supports dark mode only'], correctIndex: 1 },
  ],
  databases: [
    { id: 'q1', question: 'What does SQL stand for?', options: ['Structured Query Language', 'Simple Query Logic', 'Sequential Query List', 'Structured Question Language'], correctIndex: 0 },
    { id: 'q2', question: 'Which SQL clause is used to filter rows before grouping?', options: ['HAVING', 'WHERE', 'ORDER BY', 'GROUP BY'], correctIndex: 1 },
    { id: 'q3', question: 'What is a primary key?', options: ['Any column with text data', 'A column (or set) that uniquely identifies each row in a table', 'The first column in a table', 'A password for database access'], correctIndex: 1 },
    { id: 'q4', question: 'What kind of database is MongoDB?', options: ['Relational', 'Document-oriented NoSQL', 'Graph database', 'Key-value cache only'], correctIndex: 1 },
    { id: 'q5', question: 'What does an index primarily improve in a database?', options: ['Data encryption', 'Query read performance', 'Storage compression', 'Backup frequency'], correctIndex: 1 },
  ],
  'data-science': [
    { id: 'q1', question: 'What is the mean of the dataset [2, 4, 6, 8]?', options: ['4', '5', '6', '10'], correctIndex: 1 },
    { id: 'q2', question: 'What does a p-value below 0.05 conventionally suggest in hypothesis testing?', options: ['The null hypothesis is definitely true', 'Statistically significant evidence against the null hypothesis', 'The data is corrupted', 'No relationship exists at all'], correctIndex: 1 },
    { id: 'q3', question: 'In pandas, which method reads a CSV file into a DataFrame?', options: ['pd.load_csv()', 'pd.read_csv()', 'pd.open_csv()', 'pd.import_csv()'], correctIndex: 1 },
    { id: 'q4', question: 'What is "overfitting" in a data model?', options: ['The model performs well only on training data, poorly on new data', 'The model trains too quickly', 'The dataset is too small to load', 'The model has too few features'], correctIndex: 0 },
    { id: 'q5', question: 'Which chart type is best for showing a trend over time?', options: ['Pie chart', 'Line chart', 'Scatter plot only', 'Box plot only'], correctIndex: 1 },
  ],
  'ai-ml': [
    { id: 'q1', question: 'What is a "neural network" loosely inspired by?', options: ['Computer circuit boards', 'The structure of biological neurons', 'Database indexes', 'Cloud server clusters'], correctIndex: 1 },
    { id: 'q2', question: 'What does "supervised learning" require?', options: ['No data at all', 'Labeled training data with known outcomes', 'Only unlabeled data', 'Real-time human feedback during inference'], correctIndex: 1 },
    { id: 'q3', question: 'What is the purpose of an activation function in a neural network?', options: ['To save the model to disk', 'To introduce non-linearity so the network can learn complex patterns', 'To compress the dataset', 'To visualize training loss'], correctIndex: 1 },
    { id: 'q4', question: 'What does "backpropagation" do?', options: ['Loads data faster', 'Propagates error gradients backward to update weights', 'Reverses a trained model', 'Splits data into batches'], correctIndex: 1 },
    { id: 'q5', question: 'What is "transfer learning"?', options: ['Moving a model to a different server', 'Reusing a pretrained model as a starting point for a new task', 'Converting a model to a different language', 'Training two models simultaneously'], correctIndex: 1 },
  ],
  'cloud-devops': [
    { id: 'q1', question: 'What does IaaS stand for?', options: ['Internet as a Service', 'Infrastructure as a Service', 'Integration as a Service', 'Identity as a Service'], correctIndex: 1 },
    { id: 'q2', question: 'What is the main purpose of Docker?', options: ['Writing documentation', 'Packaging applications with their dependencies into portable containers', 'Managing DNS records', 'Encrypting databases'], correctIndex: 1 },
    { id: 'q3', question: 'In Kubernetes, what is a "Pod"?', options: ['A billing unit', 'The smallest deployable unit, wrapping one or more containers', 'A type of load balancer', 'A storage disk format'], correctIndex: 1 },
    { id: 'q4', question: 'What does CI/CD stand for?', options: ['Cloud Infrastructure / Cloud Deployment', 'Continuous Integration / Continuous Deployment', 'Code Inspection / Code Delivery', 'Container Isolation / Container Distribution'], correctIndex: 1 },
    { id: 'q5', question: 'Why use Infrastructure as Code (IaC)?', options: ['To avoid writing any documentation', 'To make infrastructure changes repeatable, versioned, and reviewable', 'To replace all cloud providers with one', 'To eliminate the need for testing'], correctIndex: 1 },
  ],
  cybersecurity: [
    { id: 'q1', question: 'What does "phishing" refer to?', options: ['A network speed test', 'Tricking users into revealing sensitive information via deceptive messages', 'A type of firewall', 'A database backup method'], correctIndex: 1 },
    { id: 'q2', question: 'What is the purpose of a firewall?', options: ['To speed up internet connections', 'To monitor and control incoming/outgoing network traffic based on rules', 'To compress files', 'To generate passwords'], correctIndex: 1 },
    { id: 'q3', question: 'What does "SQL injection" exploit?', options: ['Weak Wi-Fi passwords', 'Improperly sanitized user input in database queries', 'Slow server hardware', 'Outdated browser fonts'], correctIndex: 1 },
    { id: 'q4', question: 'What is multi-factor authentication (MFA)?', options: ['Using the same password on multiple sites', 'Requiring two or more independent credentials to verify identity', 'Encrypting a hard drive', 'A type of firewall rule'], correctIndex: 1 },
    { id: 'q5', question: 'What is the principle of "least privilege"?', options: ['Giving all users admin access for convenience', 'Granting users only the access necessary to do their job', 'Disabling all user accounts by default', 'Using the weakest available encryption'], correctIndex: 1 },
  ],
  'design-ux': [
    { id: 'q1', question: "What does Fitts's Law describe?", options: ['Color theory rules', 'The time to reach a target depends on its size and distance', 'The rule of thirds in photography', 'A typography spacing standard'], correctIndex: 1 },
    { id: 'q2', question: 'What is a "wireframe" in design?', options: ['A finished, fully-styled screen', 'A low-fidelity structural blueprint of a screen layout', 'A type of animation', 'A color palette document'], correctIndex: 1 },
    { id: 'q3', question: 'What is the main goal of usability testing?', options: ['To test server load capacity', 'To observe real users interacting with a product to find friction points', 'To check code for bugs', 'To measure font rendering speed'], correctIndex: 1 },
    { id: 'q4', question: 'What does "visual hierarchy" help users do?', options: ['Load pages faster', 'Understand what is most important on a screen at a glance', 'Change the app language', 'Reduce file size'], correctIndex: 1 },
    { id: 'q5', question: 'What is a "design system"?', options: ['A single one-off mockup', 'A reusable set of components and standards for consistent design', 'A file compression tool', 'A user survey template'], correctIndex: 1 },
  ],
  'digital-marketing': [
    { id: 'q1', question: 'What does SEO stand for?', options: ['Search Engine Optimization', 'Site Engagement Overview', 'Search Engagement Options', 'Sales Efficiency Outcome'], correctIndex: 0 },
    { id: 'q2', question: 'What is a "conversion rate"?', options: ['The exchange rate between currencies', 'The percentage of visitors who complete a desired action', 'The speed of page loading', 'The number of ads shown per day'], correctIndex: 1 },
    { id: 'q3', question: 'What is A/B testing used for?', options: ['Testing server uptime', 'Comparing two versions of something to see which performs better', 'Encrypting marketing data', 'Scheduling social media posts'], correctIndex: 1 },
    { id: 'q4', question: 'What does "organic traffic" mean?', options: ['Traffic from paid ads only', 'Visitors who arrive via unpaid search results', 'Bot traffic', 'Traffic from email campaigns only'], correctIndex: 1 },
    { id: 'q5', question: 'What is a "sales funnel"?', options: ['A physical store layout', 'The stages a customer goes through from awareness to purchase', 'A type of email filter', 'A social media algorithm'], correctIndex: 1 },
  ],
  'business-pm': [
    { id: 'q1', question: 'In project management, what does "scope creep" refer to?', options: ['A project finishing early', 'Uncontrolled expansion of a project\'s requirements over time', 'A budget surplus', 'A well-documented change request process'], correctIndex: 1 },
    { id: 'q2', question: 'What is a "stakeholder" in a project?', options: ['Only the project manager', 'Anyone with an interest in or affected by the project\'s outcome', 'Only external investors', 'A type of software tool'], correctIndex: 1 },
    { id: 'q3', question: 'What is the core idea behind Agile project management?', options: ['Planning the entire project upfront with no changes allowed', 'Iterative delivery with regular feedback and adaptation', 'Working without any documentation', 'Avoiding customer input'], correctIndex: 1 },
    { id: 'q4', question: 'What does "product-market fit" mean?', options: ['A product has a matching logo and website theme', 'A product satisfies strong market demand', 'A product is priced the same as competitors', 'A product ships on time'], correctIndex: 1 },
    { id: 'q5', question: 'What is a basic purpose of a balance sheet in finance?', options: ['To track daily expenses only', "To show a company's assets, liabilities, and equity at a point in time", 'To list employee salaries', 'To forecast weather-related risk'], correctIndex: 1 },
  ],
  'soft-skills': [
    { id: 'q1', question: 'What is "active listening"?', options: ['Waiting for your turn to speak', 'Fully concentrating on, understanding, and responding thoughtfully to a speaker', 'Taking notes without eye contact', 'Interrupting to clarify immediately'], correctIndex: 1 },
    { id: 'q2', question: 'What does the Eisenhower Matrix help you prioritize by?', options: ['Alphabetical order', 'Urgency and importance', 'Task length only', 'Who assigned the task'], correctIndex: 1 },
    { id: 'q3', question: 'What is a hallmark of effective delegation?', options: ['Assigning tasks without context', 'Matching tasks to the right skills and giving clear expectations', 'Doing all tasks yourself to ensure quality', 'Avoiding feedback after delegation'], correctIndex: 1 },
    { id: 'q4', question: 'What is "growth mindset"?', options: ['Believing abilities are fixed at birth', 'Believing abilities can be developed through effort and learning', 'Focusing only on natural talent', 'Avoiding challenges to protect self-image'], correctIndex: 1 },
    { id: 'q5', question: 'What is a key element of constructive feedback?', options: ['Being vague to avoid conflict', 'Being specific, timely, and focused on behavior rather than the person', 'Giving it only during annual reviews', 'Avoiding any positive comments'], correctIndex: 1 },
  ],
};

export function getQuizForCategory(quizCategory: string) {
  return QUIZ_BANKS[quizCategory] ?? [];
}
